package com.digital.ibatis.dao;

import com.digital.ibatis.dto.DAdminMessage;
import com.digital.ibatis.dto.DAdminMessageExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DAdminMessageDAOImpl extends SqlMapClientDaoSupport implements DAdminMessageDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public DAdminMessageDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void insert(DAdminMessage record) {
		getSqlMapClientTemplate().insert(
				"d_admin_message.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public int updateByPrimaryKey(DAdminMessage record) {
		int rows = getSqlMapClientTemplate().update(
				"d_admin_message.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public int updateByPrimaryKeySelective(DAdminMessage record) {
		int rows = getSqlMapClientTemplate().update(
				"d_admin_message.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public List selectByExample(DAdminMessageExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"d_admin_message.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public DAdminMessage selectByPrimaryKey(Integer dAdminId) {
		DAdminMessage key = new DAdminMessage();
		key.setdAdminId(dAdminId);
		DAdminMessage record = (DAdminMessage) getSqlMapClientTemplate()
				.queryForObject(
						"d_admin_message.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public int deleteByExample(DAdminMessageExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"d_admin_message.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public int deleteByPrimaryKey(Integer dAdminId) {
		DAdminMessage key = new DAdminMessage();
		key.setdAdminId(dAdminId);
		int rows = getSqlMapClientTemplate().delete(
				"d_admin_message.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public int countByExample(DAdminMessageExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"d_admin_message.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public int updateByExampleSelective(DAdminMessage record,
			DAdminMessageExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"d_admin_message.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public int updateByExample(DAdminMessage record,
			DAdminMessageExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"d_admin_message.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private static class UpdateByExampleParms extends DAdminMessageExample {
		private Object record;

		public UpdateByExampleParms(Object record, DAdminMessageExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}