package com.digital.ibatis.dao;

import com.digital.ibatis.dto.DAdminMessage;
import com.digital.ibatis.dto.DAdminMessageExample;
import java.util.List;

public interface DAdminMessageDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	void insert(DAdminMessage record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	int updateByPrimaryKey(DAdminMessage record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	int updateByPrimaryKeySelective(DAdminMessage record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	List selectByExample(DAdminMessageExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	DAdminMessage selectByPrimaryKey(Integer dAdminId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	int deleteByExample(DAdminMessageExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	int deleteByPrimaryKey(Integer dAdminId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	int countByExample(DAdminMessageExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	int updateByExampleSelective(DAdminMessage record,
			DAdminMessageExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	int updateByExample(DAdminMessage record, DAdminMessageExample example);
}