package com.digital.ibatis.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DAdminMessageExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public DAdminMessageExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	protected DAdminMessageExample(DAdminMessageExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table d_admin_message
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andDAdminIdIsNull() {
			addCriterion("d_admin_id is null");
			return this;
		}

		public Criteria andDAdminIdIsNotNull() {
			addCriterion("d_admin_id is not null");
			return this;
		}

		public Criteria andDAdminIdEqualTo(Integer value) {
			addCriterion("d_admin_id =", value, "dAdminId");
			return this;
		}

		public Criteria andDAdminIdNotEqualTo(Integer value) {
			addCriterion("d_admin_id <>", value, "dAdminId");
			return this;
		}

		public Criteria andDAdminIdGreaterThan(Integer value) {
			addCriterion("d_admin_id >", value, "dAdminId");
			return this;
		}

		public Criteria andDAdminIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("d_admin_id >=", value, "dAdminId");
			return this;
		}

		public Criteria andDAdminIdLessThan(Integer value) {
			addCriterion("d_admin_id <", value, "dAdminId");
			return this;
		}

		public Criteria andDAdminIdLessThanOrEqualTo(Integer value) {
			addCriterion("d_admin_id <=", value, "dAdminId");
			return this;
		}

		public Criteria andDAdminIdIn(List values) {
			addCriterion("d_admin_id in", values, "dAdminId");
			return this;
		}

		public Criteria andDAdminIdNotIn(List values) {
			addCriterion("d_admin_id not in", values, "dAdminId");
			return this;
		}

		public Criteria andDAdminIdBetween(Integer value1, Integer value2) {
			addCriterion("d_admin_id between", value1, value2, "dAdminId");
			return this;
		}

		public Criteria andDAdminIdNotBetween(Integer value1, Integer value2) {
			addCriterion("d_admin_id not between", value1, value2, "dAdminId");
			return this;
		}

		public Criteria andDAdminUserIsNull() {
			addCriterion("d_admin_user is null");
			return this;
		}

		public Criteria andDAdminUserIsNotNull() {
			addCriterion("d_admin_user is not null");
			return this;
		}

		public Criteria andDAdminUserEqualTo(String value) {
			addCriterion("d_admin_user =", value, "dAdminUser");
			return this;
		}

		public Criteria andDAdminUserNotEqualTo(String value) {
			addCriterion("d_admin_user <>", value, "dAdminUser");
			return this;
		}

		public Criteria andDAdminUserGreaterThan(String value) {
			addCriterion("d_admin_user >", value, "dAdminUser");
			return this;
		}

		public Criteria andDAdminUserGreaterThanOrEqualTo(String value) {
			addCriterion("d_admin_user >=", value, "dAdminUser");
			return this;
		}

		public Criteria andDAdminUserLessThan(String value) {
			addCriterion("d_admin_user <", value, "dAdminUser");
			return this;
		}

		public Criteria andDAdminUserLessThanOrEqualTo(String value) {
			addCriterion("d_admin_user <=", value, "dAdminUser");
			return this;
		}

		public Criteria andDAdminUserLike(String value) {
			addCriterion("d_admin_user like", value, "dAdminUser");
			return this;
		}

		public Criteria andDAdminUserNotLike(String value) {
			addCriterion("d_admin_user not like", value, "dAdminUser");
			return this;
		}

		public Criteria andDAdminUserIn(List values) {
			addCriterion("d_admin_user in", values, "dAdminUser");
			return this;
		}

		public Criteria andDAdminUserNotIn(List values) {
			addCriterion("d_admin_user not in", values, "dAdminUser");
			return this;
		}

		public Criteria andDAdminUserBetween(String value1, String value2) {
			addCriterion("d_admin_user between", value1, value2, "dAdminUser");
			return this;
		}

		public Criteria andDAdminUserNotBetween(String value1, String value2) {
			addCriterion("d_admin_user not between", value1, value2,
					"dAdminUser");
			return this;
		}

		public Criteria andDAdminPwdIsNull() {
			addCriterion("d_admin_pwd is null");
			return this;
		}

		public Criteria andDAdminPwdIsNotNull() {
			addCriterion("d_admin_pwd is not null");
			return this;
		}

		public Criteria andDAdminPwdEqualTo(String value) {
			addCriterion("d_admin_pwd =", value, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminPwdNotEqualTo(String value) {
			addCriterion("d_admin_pwd <>", value, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminPwdGreaterThan(String value) {
			addCriterion("d_admin_pwd >", value, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminPwdGreaterThanOrEqualTo(String value) {
			addCriterion("d_admin_pwd >=", value, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminPwdLessThan(String value) {
			addCriterion("d_admin_pwd <", value, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminPwdLessThanOrEqualTo(String value) {
			addCriterion("d_admin_pwd <=", value, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminPwdLike(String value) {
			addCriterion("d_admin_pwd like", value, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminPwdNotLike(String value) {
			addCriterion("d_admin_pwd not like", value, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminPwdIn(List values) {
			addCriterion("d_admin_pwd in", values, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminPwdNotIn(List values) {
			addCriterion("d_admin_pwd not in", values, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminPwdBetween(String value1, String value2) {
			addCriterion("d_admin_pwd between", value1, value2, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminPwdNotBetween(String value1, String value2) {
			addCriterion("d_admin_pwd not between", value1, value2, "dAdminPwd");
			return this;
		}

		public Criteria andDAdminRoleIsNull() {
			addCriterion("d_admin_role is null");
			return this;
		}

		public Criteria andDAdminRoleIsNotNull() {
			addCriterion("d_admin_role is not null");
			return this;
		}

		public Criteria andDAdminRoleEqualTo(Integer value) {
			addCriterion("d_admin_role =", value, "dAdminRole");
			return this;
		}

		public Criteria andDAdminRoleNotEqualTo(Integer value) {
			addCriterion("d_admin_role <>", value, "dAdminRole");
			return this;
		}

		public Criteria andDAdminRoleGreaterThan(Integer value) {
			addCriterion("d_admin_role >", value, "dAdminRole");
			return this;
		}

		public Criteria andDAdminRoleGreaterThanOrEqualTo(Integer value) {
			addCriterion("d_admin_role >=", value, "dAdminRole");
			return this;
		}

		public Criteria andDAdminRoleLessThan(Integer value) {
			addCriterion("d_admin_role <", value, "dAdminRole");
			return this;
		}

		public Criteria andDAdminRoleLessThanOrEqualTo(Integer value) {
			addCriterion("d_admin_role <=", value, "dAdminRole");
			return this;
		}

		public Criteria andDAdminRoleIn(List values) {
			addCriterion("d_admin_role in", values, "dAdminRole");
			return this;
		}

		public Criteria andDAdminRoleNotIn(List values) {
			addCriterion("d_admin_role not in", values, "dAdminRole");
			return this;
		}

		public Criteria andDAdminRoleBetween(Integer value1, Integer value2) {
			addCriterion("d_admin_role between", value1, value2, "dAdminRole");
			return this;
		}

		public Criteria andDAdminRoleNotBetween(Integer value1, Integer value2) {
			addCriterion("d_admin_role not between", value1, value2,
					"dAdminRole");
			return this;
		}

		public Criteria andDAdminRegTimeIsNull() {
			addCriterion("d_admin_reg_time is null");
			return this;
		}

		public Criteria andDAdminRegTimeIsNotNull() {
			addCriterion("d_admin_reg_time is not null");
			return this;
		}

		public Criteria andDAdminRegTimeEqualTo(Date value) {
			addCriterion("d_admin_reg_time =", value, "dAdminRegTime");
			return this;
		}

		public Criteria andDAdminRegTimeNotEqualTo(Date value) {
			addCriterion("d_admin_reg_time <>", value, "dAdminRegTime");
			return this;
		}

		public Criteria andDAdminRegTimeGreaterThan(Date value) {
			addCriterion("d_admin_reg_time >", value, "dAdminRegTime");
			return this;
		}

		public Criteria andDAdminRegTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("d_admin_reg_time >=", value, "dAdminRegTime");
			return this;
		}

		public Criteria andDAdminRegTimeLessThan(Date value) {
			addCriterion("d_admin_reg_time <", value, "dAdminRegTime");
			return this;
		}

		public Criteria andDAdminRegTimeLessThanOrEqualTo(Date value) {
			addCriterion("d_admin_reg_time <=", value, "dAdminRegTime");
			return this;
		}

		public Criteria andDAdminRegTimeIn(List values) {
			addCriterion("d_admin_reg_time in", values, "dAdminRegTime");
			return this;
		}

		public Criteria andDAdminRegTimeNotIn(List values) {
			addCriterion("d_admin_reg_time not in", values, "dAdminRegTime");
			return this;
		}

		public Criteria andDAdminRegTimeBetween(Date value1, Date value2) {
			addCriterion("d_admin_reg_time between", value1, value2,
					"dAdminRegTime");
			return this;
		}

		public Criteria andDAdminRegTimeNotBetween(Date value1, Date value2) {
			addCriterion("d_admin_reg_time not between", value1, value2,
					"dAdminRegTime");
			return this;
		}

		public Criteria andDAdminStateIsNull() {
			addCriterion("d_admin_state is null");
			return this;
		}

		public Criteria andDAdminStateIsNotNull() {
			addCriterion("d_admin_state is not null");
			return this;
		}

		public Criteria andDAdminStateEqualTo(Boolean value) {
			addCriterion("d_admin_state =", value, "dAdminState");
			return this;
		}

		public Criteria andDAdminStateNotEqualTo(Boolean value) {
			addCriterion("d_admin_state <>", value, "dAdminState");
			return this;
		}

		public Criteria andDAdminStateGreaterThan(Boolean value) {
			addCriterion("d_admin_state >", value, "dAdminState");
			return this;
		}

		public Criteria andDAdminStateGreaterThanOrEqualTo(Boolean value) {
			addCriterion("d_admin_state >=", value, "dAdminState");
			return this;
		}

		public Criteria andDAdminStateLessThan(Boolean value) {
			addCriterion("d_admin_state <", value, "dAdminState");
			return this;
		}

		public Criteria andDAdminStateLessThanOrEqualTo(Boolean value) {
			addCriterion("d_admin_state <=", value, "dAdminState");
			return this;
		}

		public Criteria andDAdminStateIn(List values) {
			addCriterion("d_admin_state in", values, "dAdminState");
			return this;
		}

		public Criteria andDAdminStateNotIn(List values) {
			addCriterion("d_admin_state not in", values, "dAdminState");
			return this;
		}

		public Criteria andDAdminStateBetween(Boolean value1, Boolean value2) {
			addCriterion("d_admin_state between", value1, value2, "dAdminState");
			return this;
		}

		public Criteria andDAdminStateNotBetween(Boolean value1, Boolean value2) {
			addCriterion("d_admin_state not between", value1, value2,
					"dAdminState");
			return this;
		}

		public Criteria andDAdminNoIsNull() {
			addCriterion("d_admin_no is null");
			return this;
		}

		public Criteria andDAdminNoIsNotNull() {
			addCriterion("d_admin_no is not null");
			return this;
		}

		public Criteria andDAdminNoEqualTo(String value) {
			addCriterion("d_admin_no =", value, "dAdminNo");
			return this;
		}

		public Criteria andDAdminNoNotEqualTo(String value) {
			addCriterion("d_admin_no <>", value, "dAdminNo");
			return this;
		}

		public Criteria andDAdminNoGreaterThan(String value) {
			addCriterion("d_admin_no >", value, "dAdminNo");
			return this;
		}

		public Criteria andDAdminNoGreaterThanOrEqualTo(String value) {
			addCriterion("d_admin_no >=", value, "dAdminNo");
			return this;
		}

		public Criteria andDAdminNoLessThan(String value) {
			addCriterion("d_admin_no <", value, "dAdminNo");
			return this;
		}

		public Criteria andDAdminNoLessThanOrEqualTo(String value) {
			addCriterion("d_admin_no <=", value, "dAdminNo");
			return this;
		}

		public Criteria andDAdminNoLike(String value) {
			addCriterion("d_admin_no like", value, "dAdminNo");
			return this;
		}

		public Criteria andDAdminNoNotLike(String value) {
			addCriterion("d_admin_no not like", value, "dAdminNo");
			return this;
		}

		public Criteria andDAdminNoIn(List values) {
			addCriterion("d_admin_no in", values, "dAdminNo");
			return this;
		}

		public Criteria andDAdminNoNotIn(List values) {
			addCriterion("d_admin_no not in", values, "dAdminNo");
			return this;
		}

		public Criteria andDAdminNoBetween(String value1, String value2) {
			addCriterion("d_admin_no between", value1, value2, "dAdminNo");
			return this;
		}

		public Criteria andDAdminNoNotBetween(String value1, String value2) {
			addCriterion("d_admin_no not between", value1, value2, "dAdminNo");
			return this;
		}

		public Criteria andDAdminGenderIsNull() {
			addCriterion("d_admin_gender is null");
			return this;
		}

		public Criteria andDAdminGenderIsNotNull() {
			addCriterion("d_admin_gender is not null");
			return this;
		}

		public Criteria andDAdminGenderEqualTo(Integer value) {
			addCriterion("d_admin_gender =", value, "dAdminGender");
			return this;
		}

		public Criteria andDAdminGenderNotEqualTo(Integer value) {
			addCriterion("d_admin_gender <>", value, "dAdminGender");
			return this;
		}

		public Criteria andDAdminGenderGreaterThan(Integer value) {
			addCriterion("d_admin_gender >", value, "dAdminGender");
			return this;
		}

		public Criteria andDAdminGenderGreaterThanOrEqualTo(Integer value) {
			addCriterion("d_admin_gender >=", value, "dAdminGender");
			return this;
		}

		public Criteria andDAdminGenderLessThan(Integer value) {
			addCriterion("d_admin_gender <", value, "dAdminGender");
			return this;
		}

		public Criteria andDAdminGenderLessThanOrEqualTo(Integer value) {
			addCriterion("d_admin_gender <=", value, "dAdminGender");
			return this;
		}

		public Criteria andDAdminGenderIn(List values) {
			addCriterion("d_admin_gender in", values, "dAdminGender");
			return this;
		}

		public Criteria andDAdminGenderNotIn(List values) {
			addCriterion("d_admin_gender not in", values, "dAdminGender");
			return this;
		}

		public Criteria andDAdminGenderBetween(Integer value1, Integer value2) {
			addCriterion("d_admin_gender between", value1, value2,
					"dAdminGender");
			return this;
		}

		public Criteria andDAdminGenderNotBetween(Integer value1, Integer value2) {
			addCriterion("d_admin_gender not between", value1, value2,
					"dAdminGender");
			return this;
		}

		public Criteria andDAdminTelIsNull() {
			addCriterion("d_admin_tel is null");
			return this;
		}

		public Criteria andDAdminTelIsNotNull() {
			addCriterion("d_admin_tel is not null");
			return this;
		}

		public Criteria andDAdminTelEqualTo(String value) {
			addCriterion("d_admin_tel =", value, "dAdminTel");
			return this;
		}

		public Criteria andDAdminTelNotEqualTo(String value) {
			addCriterion("d_admin_tel <>", value, "dAdminTel");
			return this;
		}

		public Criteria andDAdminTelGreaterThan(String value) {
			addCriterion("d_admin_tel >", value, "dAdminTel");
			return this;
		}

		public Criteria andDAdminTelGreaterThanOrEqualTo(String value) {
			addCriterion("d_admin_tel >=", value, "dAdminTel");
			return this;
		}

		public Criteria andDAdminTelLessThan(String value) {
			addCriterion("d_admin_tel <", value, "dAdminTel");
			return this;
		}

		public Criteria andDAdminTelLessThanOrEqualTo(String value) {
			addCriterion("d_admin_tel <=", value, "dAdminTel");
			return this;
		}

		public Criteria andDAdminTelLike(String value) {
			addCriterion("d_admin_tel like", value, "dAdminTel");
			return this;
		}

		public Criteria andDAdminTelNotLike(String value) {
			addCriterion("d_admin_tel not like", value, "dAdminTel");
			return this;
		}

		public Criteria andDAdminTelIn(List values) {
			addCriterion("d_admin_tel in", values, "dAdminTel");
			return this;
		}

		public Criteria andDAdminTelNotIn(List values) {
			addCriterion("d_admin_tel not in", values, "dAdminTel");
			return this;
		}

		public Criteria andDAdminTelBetween(String value1, String value2) {
			addCriterion("d_admin_tel between", value1, value2, "dAdminTel");
			return this;
		}

		public Criteria andDAdminTelNotBetween(String value1, String value2) {
			addCriterion("d_admin_tel not between", value1, value2, "dAdminTel");
			return this;
		}

		public Criteria andDAdminAddressIsNull() {
			addCriterion("d_admin_address is null");
			return this;
		}

		public Criteria andDAdminAddressIsNotNull() {
			addCriterion("d_admin_address is not null");
			return this;
		}

		public Criteria andDAdminAddressEqualTo(String value) {
			addCriterion("d_admin_address =", value, "dAdminAddress");
			return this;
		}

		public Criteria andDAdminAddressNotEqualTo(String value) {
			addCriterion("d_admin_address <>", value, "dAdminAddress");
			return this;
		}

		public Criteria andDAdminAddressGreaterThan(String value) {
			addCriterion("d_admin_address >", value, "dAdminAddress");
			return this;
		}

		public Criteria andDAdminAddressGreaterThanOrEqualTo(String value) {
			addCriterion("d_admin_address >=", value, "dAdminAddress");
			return this;
		}

		public Criteria andDAdminAddressLessThan(String value) {
			addCriterion("d_admin_address <", value, "dAdminAddress");
			return this;
		}

		public Criteria andDAdminAddressLessThanOrEqualTo(String value) {
			addCriterion("d_admin_address <=", value, "dAdminAddress");
			return this;
		}

		public Criteria andDAdminAddressLike(String value) {
			addCriterion("d_admin_address like", value, "dAdminAddress");
			return this;
		}

		public Criteria andDAdminAddressNotLike(String value) {
			addCriterion("d_admin_address not like", value, "dAdminAddress");
			return this;
		}

		public Criteria andDAdminAddressIn(List values) {
			addCriterion("d_admin_address in", values, "dAdminAddress");
			return this;
		}

		public Criteria andDAdminAddressNotIn(List values) {
			addCriterion("d_admin_address not in", values, "dAdminAddress");
			return this;
		}

		public Criteria andDAdminAddressBetween(String value1, String value2) {
			addCriterion("d_admin_address between", value1, value2,
					"dAdminAddress");
			return this;
		}

		public Criteria andDAdminAddressNotBetween(String value1, String value2) {
			addCriterion("d_admin_address not between", value1, value2,
					"dAdminAddress");
			return this;
		}

		public Criteria andDAdminLastTimeIsNull() {
			addCriterion("d_admin_last_time is null");
			return this;
		}

		public Criteria andDAdminLastTimeIsNotNull() {
			addCriterion("d_admin_last_time is not null");
			return this;
		}

		public Criteria andDAdminLastTimeEqualTo(Date value) {
			addCriterion("d_admin_last_time =", value, "dAdminLastTime");
			return this;
		}

		public Criteria andDAdminLastTimeNotEqualTo(Date value) {
			addCriterion("d_admin_last_time <>", value, "dAdminLastTime");
			return this;
		}

		public Criteria andDAdminLastTimeGreaterThan(Date value) {
			addCriterion("d_admin_last_time >", value, "dAdminLastTime");
			return this;
		}

		public Criteria andDAdminLastTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("d_admin_last_time >=", value, "dAdminLastTime");
			return this;
		}

		public Criteria andDAdminLastTimeLessThan(Date value) {
			addCriterion("d_admin_last_time <", value, "dAdminLastTime");
			return this;
		}

		public Criteria andDAdminLastTimeLessThanOrEqualTo(Date value) {
			addCriterion("d_admin_last_time <=", value, "dAdminLastTime");
			return this;
		}

		public Criteria andDAdminLastTimeIn(List values) {
			addCriterion("d_admin_last_time in", values, "dAdminLastTime");
			return this;
		}

		public Criteria andDAdminLastTimeNotIn(List values) {
			addCriterion("d_admin_last_time not in", values, "dAdminLastTime");
			return this;
		}

		public Criteria andDAdminLastTimeBetween(Date value1, Date value2) {
			addCriterion("d_admin_last_time between", value1, value2,
					"dAdminLastTime");
			return this;
		}

		public Criteria andDAdminLastTimeNotBetween(Date value1, Date value2) {
			addCriterion("d_admin_last_time not between", value1, value2,
					"dAdminLastTime");
			return this;
		}

		public Criteria andDAdminLastIpIsNull() {
			addCriterion("d_admin_last_ip is null");
			return this;
		}

		public Criteria andDAdminLastIpIsNotNull() {
			addCriterion("d_admin_last_ip is not null");
			return this;
		}

		public Criteria andDAdminLastIpEqualTo(String value) {
			addCriterion("d_admin_last_ip =", value, "dAdminLastIp");
			return this;
		}

		public Criteria andDAdminLastIpNotEqualTo(String value) {
			addCriterion("d_admin_last_ip <>", value, "dAdminLastIp");
			return this;
		}

		public Criteria andDAdminLastIpGreaterThan(String value) {
			addCriterion("d_admin_last_ip >", value, "dAdminLastIp");
			return this;
		}

		public Criteria andDAdminLastIpGreaterThanOrEqualTo(String value) {
			addCriterion("d_admin_last_ip >=", value, "dAdminLastIp");
			return this;
		}

		public Criteria andDAdminLastIpLessThan(String value) {
			addCriterion("d_admin_last_ip <", value, "dAdminLastIp");
			return this;
		}

		public Criteria andDAdminLastIpLessThanOrEqualTo(String value) {
			addCriterion("d_admin_last_ip <=", value, "dAdminLastIp");
			return this;
		}

		public Criteria andDAdminLastIpLike(String value) {
			addCriterion("d_admin_last_ip like", value, "dAdminLastIp");
			return this;
		}

		public Criteria andDAdminLastIpNotLike(String value) {
			addCriterion("d_admin_last_ip not like", value, "dAdminLastIp");
			return this;
		}

		public Criteria andDAdminLastIpIn(List values) {
			addCriterion("d_admin_last_ip in", values, "dAdminLastIp");
			return this;
		}

		public Criteria andDAdminLastIpNotIn(List values) {
			addCriterion("d_admin_last_ip not in", values, "dAdminLastIp");
			return this;
		}

		public Criteria andDAdminLastIpBetween(String value1, String value2) {
			addCriterion("d_admin_last_ip between", value1, value2,
					"dAdminLastIp");
			return this;
		}

		public Criteria andDAdminLastIpNotBetween(String value1, String value2) {
			addCriterion("d_admin_last_ip not between", value1, value2,
					"dAdminLastIp");
			return this;
		}

		public Criteria andDAdminRemarkIsNull() {
			addCriterion("d_admin_remark is null");
			return this;
		}

		public Criteria andDAdminRemarkIsNotNull() {
			addCriterion("d_admin_remark is not null");
			return this;
		}

		public Criteria andDAdminRemarkEqualTo(String value) {
			addCriterion("d_admin_remark =", value, "dAdminRemark");
			return this;
		}

		public Criteria andDAdminRemarkNotEqualTo(String value) {
			addCriterion("d_admin_remark <>", value, "dAdminRemark");
			return this;
		}

		public Criteria andDAdminRemarkGreaterThan(String value) {
			addCriterion("d_admin_remark >", value, "dAdminRemark");
			return this;
		}

		public Criteria andDAdminRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("d_admin_remark >=", value, "dAdminRemark");
			return this;
		}

		public Criteria andDAdminRemarkLessThan(String value) {
			addCriterion("d_admin_remark <", value, "dAdminRemark");
			return this;
		}

		public Criteria andDAdminRemarkLessThanOrEqualTo(String value) {
			addCriterion("d_admin_remark <=", value, "dAdminRemark");
			return this;
		}

		public Criteria andDAdminRemarkLike(String value) {
			addCriterion("d_admin_remark like", value, "dAdminRemark");
			return this;
		}

		public Criteria andDAdminRemarkNotLike(String value) {
			addCriterion("d_admin_remark not like", value, "dAdminRemark");
			return this;
		}

		public Criteria andDAdminRemarkIn(List values) {
			addCriterion("d_admin_remark in", values, "dAdminRemark");
			return this;
		}

		public Criteria andDAdminRemarkNotIn(List values) {
			addCriterion("d_admin_remark not in", values, "dAdminRemark");
			return this;
		}

		public Criteria andDAdminRemarkBetween(String value1, String value2) {
			addCriterion("d_admin_remark between", value1, value2,
					"dAdminRemark");
			return this;
		}

		public Criteria andDAdminRemarkNotBetween(String value1, String value2) {
			addCriterion("d_admin_remark not between", value1, value2,
					"dAdminRemark");
			return this;
		}

		public Criteria andDAdminPermissionIsNull() {
			addCriterion("d_admin_permission is null");
			return this;
		}

		public Criteria andDAdminPermissionIsNotNull() {
			addCriterion("d_admin_permission is not null");
			return this;
		}

		public Criteria andDAdminPermissionEqualTo(String value) {
			addCriterion("d_admin_permission =", value, "dAdminPermission");
			return this;
		}

		public Criteria andDAdminPermissionNotEqualTo(String value) {
			addCriterion("d_admin_permission <>", value, "dAdminPermission");
			return this;
		}

		public Criteria andDAdminPermissionGreaterThan(String value) {
			addCriterion("d_admin_permission >", value, "dAdminPermission");
			return this;
		}

		public Criteria andDAdminPermissionGreaterThanOrEqualTo(String value) {
			addCriterion("d_admin_permission >=", value, "dAdminPermission");
			return this;
		}

		public Criteria andDAdminPermissionLessThan(String value) {
			addCriterion("d_admin_permission <", value, "dAdminPermission");
			return this;
		}

		public Criteria andDAdminPermissionLessThanOrEqualTo(String value) {
			addCriterion("d_admin_permission <=", value, "dAdminPermission");
			return this;
		}

		public Criteria andDAdminPermissionLike(String value) {
			addCriterion("d_admin_permission like", value, "dAdminPermission");
			return this;
		}

		public Criteria andDAdminPermissionNotLike(String value) {
			addCriterion("d_admin_permission not like", value,
					"dAdminPermission");
			return this;
		}

		public Criteria andDAdminPermissionIn(List values) {
			addCriterion("d_admin_permission in", values, "dAdminPermission");
			return this;
		}

		public Criteria andDAdminPermissionNotIn(List values) {
			addCriterion("d_admin_permission not in", values,
					"dAdminPermission");
			return this;
		}

		public Criteria andDAdminPermissionBetween(String value1, String value2) {
			addCriterion("d_admin_permission between", value1, value2,
					"dAdminPermission");
			return this;
		}

		public Criteria andDAdminPermissionNotBetween(String value1,
				String value2) {
			addCriterion("d_admin_permission not between", value1, value2,
					"dAdminPermission");
			return this;
		}
	}
}