package com.digital.ibatis.dto;

import java.util.Date;

public class DAdminMessage {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_id
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private Integer dAdminId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_user
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private String dAdminUser;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_pwd
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private String dAdminPwd;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_role
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private Integer dAdminRole;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_reg_time
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private Date dAdminRegTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_state
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private Boolean dAdminState;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_no
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private String dAdminNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_gender
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private Integer dAdminGender;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_tel
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private String dAdminTel;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_address
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private String dAdminAddress;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_last_time
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private Date dAdminLastTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_last_ip
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private String dAdminLastIp;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_remark
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private String dAdminRemark;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column d_admin_message.d_admin_permission
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	private String dAdminPermission;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_id
	 * @return  the value of d_admin_message.d_admin_id
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public Integer getdAdminId() {
		return dAdminId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_id
	 * @param dAdminId  the value for d_admin_message.d_admin_id
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminId(Integer dAdminId) {
		this.dAdminId = dAdminId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_user
	 * @return  the value of d_admin_message.d_admin_user
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public String getdAdminUser() {
		return dAdminUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_user
	 * @param dAdminUser  the value for d_admin_message.d_admin_user
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminUser(String dAdminUser) {
		this.dAdminUser = dAdminUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_pwd
	 * @return  the value of d_admin_message.d_admin_pwd
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public String getdAdminPwd() {
		return dAdminPwd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_pwd
	 * @param dAdminPwd  the value for d_admin_message.d_admin_pwd
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminPwd(String dAdminPwd) {
		this.dAdminPwd = dAdminPwd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_role
	 * @return  the value of d_admin_message.d_admin_role
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public Integer getdAdminRole() {
		return dAdminRole;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_role
	 * @param dAdminRole  the value for d_admin_message.d_admin_role
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminRole(Integer dAdminRole) {
		this.dAdminRole = dAdminRole;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_reg_time
	 * @return  the value of d_admin_message.d_admin_reg_time
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public Date getdAdminRegTime() {
		return dAdminRegTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_reg_time
	 * @param dAdminRegTime  the value for d_admin_message.d_admin_reg_time
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminRegTime(Date dAdminRegTime) {
		this.dAdminRegTime = dAdminRegTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_state
	 * @return  the value of d_admin_message.d_admin_state
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public Boolean getdAdminState() {
		return dAdminState;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_state
	 * @param dAdminState  the value for d_admin_message.d_admin_state
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminState(Boolean dAdminState) {
		this.dAdminState = dAdminState;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_no
	 * @return  the value of d_admin_message.d_admin_no
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public String getdAdminNo() {
		return dAdminNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_no
	 * @param dAdminNo  the value for d_admin_message.d_admin_no
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminNo(String dAdminNo) {
		this.dAdminNo = dAdminNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_gender
	 * @return  the value of d_admin_message.d_admin_gender
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public Integer getdAdminGender() {
		return dAdminGender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_gender
	 * @param dAdminGender  the value for d_admin_message.d_admin_gender
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminGender(Integer dAdminGender) {
		this.dAdminGender = dAdminGender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_tel
	 * @return  the value of d_admin_message.d_admin_tel
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public String getdAdminTel() {
		return dAdminTel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_tel
	 * @param dAdminTel  the value for d_admin_message.d_admin_tel
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminTel(String dAdminTel) {
		this.dAdminTel = dAdminTel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_address
	 * @return  the value of d_admin_message.d_admin_address
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public String getdAdminAddress() {
		return dAdminAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_address
	 * @param dAdminAddress  the value for d_admin_message.d_admin_address
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminAddress(String dAdminAddress) {
		this.dAdminAddress = dAdminAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_last_time
	 * @return  the value of d_admin_message.d_admin_last_time
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public Date getdAdminLastTime() {
		return dAdminLastTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_last_time
	 * @param dAdminLastTime  the value for d_admin_message.d_admin_last_time
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminLastTime(Date dAdminLastTime) {
		this.dAdminLastTime = dAdminLastTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_last_ip
	 * @return  the value of d_admin_message.d_admin_last_ip
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public String getdAdminLastIp() {
		return dAdminLastIp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_last_ip
	 * @param dAdminLastIp  the value for d_admin_message.d_admin_last_ip
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminLastIp(String dAdminLastIp) {
		this.dAdminLastIp = dAdminLastIp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_remark
	 * @return  the value of d_admin_message.d_admin_remark
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public String getdAdminRemark() {
		return dAdminRemark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_remark
	 * @param dAdminRemark  the value for d_admin_message.d_admin_remark
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminRemark(String dAdminRemark) {
		this.dAdminRemark = dAdminRemark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column d_admin_message.d_admin_permission
	 * @return  the value of d_admin_message.d_admin_permission
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public String getdAdminPermission() {
		return dAdminPermission;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column d_admin_message.d_admin_permission
	 * @param dAdminPermission  the value for d_admin_message.d_admin_permission
	 * @abatorgenerated  Fri Dec 27 08:56:29 CST 2013
	 */
	public void setdAdminPermission(String dAdminPermission) {
		this.dAdminPermission = dAdminPermission;
	}
    
}